import {
  CITIES,
  REGIONS,
  TOTAL_CITY_COUNT,
  getCityBySlug,
  nearbyCities,
  type CityData,
  type RegionMeta,
} from "./serviceAreas";
import { INDUSTRIES } from "./industries";

/**
 * Per-city copy, generated by a template driven by real per-city variables
 * (county, ZIP, region character, industry emphasis) — not 37 hand-written
 * blurbs, and not a bare city-name swap.
 *
 * No fabricated proof points anywhere in this file: no invented project
 * counts, client names, testimonials, or per-city offices. Copy deliberately
 * doesn't discuss where TWS's office is or where crews are dispatched from —
 * that's a business framing choice, not a factual claim being made either way.
 */

export interface LocationContent {
  metaTitle: string;
  metaDescription: string;
  heroEyebrow: string;
  heroBody: string;
  /** The primary, keyword-focused <h1> text for this page — real service +
   *  city name, not the generic brand tagline (which becomes a supporting
   *  sub-line under this when present). */
  heroHeadline: string;
  trustCoverageValue: string;
  ctaServiceAreaValue: string;
  /** Short, scannable — the compact "Serving {city}" card next to the map. */
  cardSummary: string;
  /** One consolidated supporting paragraph, below the map — real facts only. */
  paragraph: string;
  faq: { question: string; answer: string }[];
  mapEmbedSrc: string;
  mapCaption: string;
}

export interface CityPageData {
  city: CityData;
  region: RegionMeta;
  content: LocationContent;
  nearby: CityData[];
}

function industryLabel(key: string): string {
  const labels: Record<string, string> = {
    healthcare: "healthcare",
    airport: "airports",
    lab: "labs",
    office: "offices",
    retail: "retail",
    school: "schools",
    telecom: "telecom",
    events: "venues",
    government: "government buildings",
  };
  return labels[key] ?? key;
}

function buildFaq(city: CityData, region: RegionMeta) {
  const industryListPhrase = region.emphasisIndustries.map(industryLabel).join(", ");

  return [
    {
      question: `Do you install ICRA containment in ${city.name}?`,
      answer: `Yes — ${city.name} is part of our regular ${region.name} coverage, one of ${TOTAL_CITY_COUNT} cities we serve from the Treasure Coast down to Miami.`,
    },
    {
      question: "Do you handle removal when the project wraps?",
      answer: "Yes — removal is part of every installation, not a separate call. We take the barrier down and leave the space clean when the job is done.",
    },
    {
      question: `What areas near ${city.name} do you cover?`,
      answer: `We work throughout ${city.county} (ZIP ${city.zip}) and the rest of the ${region.name} corridor.`,
    },
    {
      question: "What ICRA classes can you build to?",
      answer: "Class I through IV barrier construction — negative-pressure ready, HEPA and airlock compatible, with documentation prepared for infection-control survey.",
    },
    {
      question: `What kinds of buildings do you work on around ${city.name}?`,
      answer: `Mostly ${industryListPhrase} — that's the mix of work we see most often in ${city.county}.`,
    },
  ];
}

export function getCityPageData(slug: string): CityPageData | undefined {
  const cityData = getCityBySlug(slug);
  if (!cityData) return undefined;
  const region = REGIONS[cityData.regionKey];
  const nearby = nearbyCities(cityData);

  const secondaryIndustry = industryLabel(
    region.emphasisIndustries.find((k) => k !== "healthcare") ?? region.emphasisIndustries[0]
  );
  const industryListPhrase = region.emphasisIndustries.map((k) => INDUSTRIES[k].label).join(", ");

  const cardSummary = `We install ICRA-rated containment at healthcare, ${secondaryIndustry}, and commercial properties around ${cityData.name} — same Class I–IV barrier standards on every job, wherever it's built.`;

  const paragraph = `${cityData.name} is part of ${cityData.county}, ${region.regionCharacter}. Most of what we build here is for ${industryListPhrase.toLowerCase()} — the area's dominant sectors — so the crew already knows the inspection standards and after-hours access windows those buildings run on.`;

  const content: LocationContent = {
    metaTitle: `ICRA Temporary Wall Containment in ${cityData.name}, FL | TWS Southeast Florida`,
    metaDescription: `TWS installs ICRA-rated modular containment walls in ${cityData.name}, ${cityData.county} (${cityData.zip}) — ${region.name} coverage.`,
    heroEyebrow: `ICRA-Rated Containment · ${cityData.name}, FL`,
    heroBody: `ICRA-rated modular walls for healthcare, ${secondaryIndustry}, and more in ${cityData.name} and the rest of ${region.name} — reconfigured between phases, removed without a trace.`,
    heroHeadline: `ICRA Containment in ${cityData.name}, FL`,
    trustCoverageValue: `${cityData.name}, FL`,
    ctaServiceAreaValue: `${cityData.name} · ${cityData.county}`,
    cardSummary,
    paragraph,
    faq: buildFaq(cityData, region),
    mapEmbedSrc: `https://maps.google.com/maps?q=${encodeURIComponent(`${cityData.name}, FL, USA`)}&output=embed`,
    mapCaption: `Proudly serving ${cityData.name}, FL and the surrounding area.`,
  };

  return { city: cityData, region, content, nearby };
}

export function getAllCitySlugs(): string[] {
  return CITIES.map((c) => c.slug);
}
